### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dmontecino** [drostlab/myTAI#6]
Thanks for the package! works great. 

I think an option avoiding the "which row do you want" when there are more than 2 matches (I had that with "Camel" and the Bactrian and dromedary ones. For example, if more than one row get the first one or assign a "MOre than one option" fill. 

I get a loop stopped because of it. 

Completely constructive mood. Thanks

**Comment by HajkD** [comment]
Hi @dmontecino 

Many thanks for contacting me and I am happy to hear that you find `myTAI` useful for your research.

I am happy to incorporate your suggestions into the new version of `myTAI`.

Would it be possible to be a bit more specific and give some more details so that I can make sure that I correctly understood what you are pointing at? E.g. which concrete functions do you have in mind?

Many thanks,
Hajk

**Comment by dmontecino** [comment]
Actually, that was very poorly written. I was using your package to get the taxonomy of several species, based on their common name (if I remember correctly). I am doing this with a for loop or lapply/map. It runs great, but when 2 or more matches are found, the loop stops and there is a screen popping up asking me which of the found options I want. It stops the process until answered (parallel computing I tried is not accepted by the server). So my suggestion was, could you add a parameter in the function to choose to include all matches that avoids getting asked which option I want? I hope this is a better explanation. Thanks for reaching out
